=begin
Lista de Usuários

API que provê acesso aos usuários do sistema

OpenAPI spec version: 0.0.1
Contact: denilso.brustelo@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Error < ApplicationRecord

end
