=begin
Lista de Usuários

API que provê acesso aos usuários do sistema

OpenAPI spec version: 0.0.1
Contact: denilso.brustelo@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UsersController < ApplicationController

  def index
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def destroy
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def show
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def users_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def users_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
