=begin
Lista de Usuários

API que provê acesso aos usuários do sistema

OpenAPI spec version: 0.0.1
Contact: denilso.brustelo@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :message
      t.string :fields

      t.timestamps
    end

    create_table "user".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :email
      t.string :name

      t.timestamps
    end

  end
end
